COMMON: &common #标识
  DEBUG: False
  SECRET_KEY: insecure
  # 页码设置
  DEFAULT_PAGE_INDEX: 1
  DEFAULT_PAGE_SIZE: 10

  # 数据库连接
  SQLALCHEMY_DATABASE_URI: 'mysql+pymysql://root:mad123@localhost:3306/test?charset=utf8mb4'
  SQLALCHEMY_TRACK_MODIFICATIONS: False
  # 日志配置文件路径
  LOGGING_CONFIG_PATH: ./config/logging.yaml
  # 日志文件存放位置
  LOGGING_PATH: ./logs

  # 响应消息
  RESPONSE_MESSAGE: ./config/msg.yaml

  # redis配置
  REDIS_EXPIRE: 60*60
  REDIS_HOST: 127.0.0.1
  REDIS_PORT: 6379
  REDIS_DB: 1

DEVELOPMENT: &development
  <<: *common # 继承common，没有重新定义的变量，使用common变量值
  DEBUG: True

STAGING: &staging
  <<: *common
  SECRET_KEY: sortasecure

PRODUCTION: &production
  <<: *common
  SECRET_KEY: mdd1##$$%^!DSA#FDSF